// import dayjs from "dayjs";

// function getTime(day = 0, second = 0) {
//   return dayjs().add(day, "days").add(second, "seconds").format("YYYY.MM.DD HH:mm:ss");
// }

// export const initData = async (clientId, nextSeq) => {
//   return {
//     // 회원
//     user: [
//       {
//         _id: await nextSeq("user"),
//         email: "seller@market.com",
//         password: "$2b$10$S.8GNMDyvUF0xzujPtHBu.j5gtS19.OhRmYbpJBnCHg2S83WLx1T2",
//         name: "판매자",
//         phone: "01033334444",
//         address: "서울시 서초구 반포동 817",
//         type: "seller",
//         loginType: "email",
//         createdAt: getTime(-40),
//         updatedAt: getTime(-20, -60 * 60 * 2),
//         extra: {
//           address: {
//             zipCode: "06501",
//             mainAddress: "서울시 서초구 반포동 817",
//             detailAddress: "201동 1301호",
//           },
//         },
//       },
//       {
//         _id: await nextSeq("user"),
//         email: "karina@market.com",
//         password: "$2b$10$S.8GNMDyvUF0xzujPtHBu.j5gtS19.OhRmYbpJBnCHg2S83WLx1T2",
//         name: "카리나",
//         phone: "01033334444",
//         address: "서울시 서초구 반포동 817",
//         type: "user",
//         loginType: "email",
//         createdAt: getTime(-40),
//         updatedAt: getTime(-20, -60 * 60 * 2),
//         extra: {
//           address: {
//             zipCode: "06501",
//             mainAddress: "서울시 서초구 반포동 817",
//             detailAddress: "201동 1301호",
//           },
//         },
//       },
//       {
//         _id: await nextSeq("user"),
//         email: "eunwoo@market.com",
//         password: "$2b$10$S.8GNMDyvUF0xzujPtHBu.j5gtS19.OhRmYbpJBnCHg2S83WLx1T2",
//         name: "차은우",
//         phone: "01044445555",
//         address: "서울시 송파구 잠실동 123",
//         type: "user",
//         loginType: "email",
//         createdAt: getTime(-35),
//         updatedAt: getTime(-10, -60 * 60 * 1),
//         extra: {
//           address: {
//             zipCode: "06911",
//             mainAddress: "서울특별시 동작구 흑석동 204-104",
//             detailAddress: "102동 201호",
//           },
//         },
//       },
//     ],

//     // 상품
//     product: [
//       {
//         _id: await nextSeq("product"),
//         seller_id: 1,
//         price: 32000,
//         show: true,
//         active: true,
//         name: "라벤더 드림 퍼퓸",
//         quantity: 150,
//         buyQuantity: 89,
//         mainImages: [
//           {
//             path: `files/${clientId}/perfume1.webp`,
//             name: "perfume1.webp",
//             originalname: "라벤더드림.webp",
//           },
//         ],
//         createdAt: getTime(-41, -60 * 60 * 2),
//         updatedAt: getTime(-40, -60 * 15),
//         extra: {
//           mainAccord: "woody",
//           brand: "조말론",
//           brandInitialKR: "ㅈ",
//           volumes: [50, 80, 100],
//           prices: [57900, 82900, 99900],
//           tags: ["우디", "고급스러움", "차분함", "중성적", "가을/겨울"],
//           content: "깊은 나무 향이 마음을 차분하게 만드는 우디 퍼퓸.",
//           detailContent: "삼나무와 샌달우드가 어우러져 안정감 있는 향을 전달합니다. 도심 속 자연을 느끼게 하는 감성적인 향수입니다.",
//         },
//       },
//       {
//         _id: await nextSeq("product"),
//         seller_id: 1,
//         price: 32000,
//         show: true,
//         active: true,
//         name: "로지 블룸 퍼퓸",
//         quantity: 150,
//         buyQuantity: 102,
//         mainImages: [
//           {
//             path: `files/${clientId}/perfume2.webp`,
//             name: "perfume2.webp",
//             originalname: "로지블룸.webp",
//           },
//         ],
//         createdAt: getTime(-41, -60 * 60 * 2),
//         updatedAt: getTime(-40, -60 * 15),
//         extra: {
//           mainAccord: "floral",
//           brand: "딥디크",
//           brandInitialKR: "ㄷ",
//           volumes: [30, 50, 100],
//           prices: [49900, 72900, 97900],
//           tags: ["플로럴", "사랑스러움", "데이트", "은은함", "샤워코롱"],
//           content: "은은한 장미 향으로 기분 좋은 하루를 시작해보세요.",
//           detailContent: "싱그러운 장미 꽃잎이 피부에 살짝 닿은 듯한 느낌을 줍니다. 누구에게나 부담 없는 사랑스러운 향입니다.",
//         },
//       },
//       {
//         _id: await nextSeq("product"),
//         seller_id: 1,
//         price: 32000,
//         show: true,
//         active: true,
//         name: "무스크 헤이븐 퍼퓸",
//         quantity: 150,
//         buyQuantity: 73,
//         mainImages: [
//           {
//             path: `files/${clientId}/perfume3.webp`,
//             name: "perfume3.webp",
//             originalname: "무스크헤이븐.webp",
//           },
//         ],
//         createdAt: getTime(-41, -60 * 60 * 2),
//         updatedAt: getTime(-40, -60 * 15),
//         extra: {
//           mainAccord: "musk",
//           brand: "에르메스",
//           brandInitialKR: "ㅇ",
//           volumes: [50, 75, 100],
//           prices: [58900, 81900, 104900],
//           tags: ["머스크", "부드러움", "중성적", "지속력 좋음", "데일리"],
//           content: "포근한 머스크 향이 부드럽게 감싸는 데일리 향수.",
//           detailContent: "살냄새처럼 자연스럽게 어우러지는 머스크 노트가 잔잔하게 퍼지며 하루 종일 포근함을 유지합니다.",
//         },
//       },
//       {
//         _id: await nextSeq("product"),
//         seller_id: 1,
//         price: 32000,
//         show: true,
//         active: true,
//         name: "스위트 시나몬 퍼퓸",
//         quantity: 150,
//         buyQuantity: 68,
//         mainImages: [
//           {
//             path: `files/${clientId}/perfume4.webp`,
//             name: "perfume4.webp",
//             originalname: "스위트시나몬.webp",
//           },
//         ],
//         createdAt: getTime(-41, -60 * 60 * 2),
//         updatedAt: getTime(-40, -60 * 15),
//         extra: {
//           mainAccord: "sweet",
//           brand: "바이레도",
//           brandInitialKR: "ㅂ",
//           volumes: [40, 70, 100],
//           prices: [53900, 79900, 95900],
//           tags: ["달콤함", "시나몬", "포근함", "겨울", "스페셜"],
//           content: "시나몬의 달콤함이 퍼지는 중독성 강한 겨울 향수.",
//           detailContent: "달콤한 바닐라와 시나몬이 따뜻한 분위기를 연출합니다. 특별한 날에 잘 어울리는 포근한 무드.",
//         },
//       },
//       {
//         _id: await nextSeq("product"),
//         seller_id: 1,
//         price: 32000,
//         show: true,
//         active: true,
//         name: "시트러스 브리즈 퍼퓸",
//         quantity: 150,
//         buyQuantity: 95,
//         mainImages: [
//           {
//             path: `files/${clientId}/perfume5.webp`,
//             name: "perfume5.webp",
//             originalname: "시트러스브리즈.webp",
//           },
//         ],
//         createdAt: getTime(-41, -60 * 60 * 2),
//         updatedAt: getTime(-40, -60 * 15),
//         extra: {
//           mainAccord: "citrus",
//           brand: "르 라보",
//           brandInitialKR: "ㄹ",
//           volumes: [30, 60, 100],
//           prices: [44900, 70900, 95900],
//           tags: ["시트러스", "상큼함", "샤워코롱", "여름", "프레시"],
//           content: "상큼한 과일 향이 폭발하는 여름 전용 퍼퓸.",
//           detailContent: "자몽과 레몬의 프레시함이 뿜어져 나오며 활기찬 무드를 선사합니다. 샤워 직후 같은 깨끗함이 오래 지속됩니다.",
//         },
//       },
//       {
//         _id: await nextSeq("product"),
//         seller_id: 1,
//         price: 32000,
//         show: true,
//         active: true,
//         name: "우디 네롤리 퍼퓸",
//         quantity: 150,
//         buyQuantity: 57,
//         mainImages: [
//           {
//             path: `files/${clientId}/perfume6.webp`,
//             name: "perfume6.webp",
//             originalname: "우디네롤리.webp",
//           },
//         ],
//         createdAt: getTime(-41, -60 * 60 * 2),
//         updatedAt: getTime(-40, -60 * 15),
//         extra: {
//           mainAccord: "woody",
//           brand: "펜할리곤스",
//           brandInitialKR: "ㅍ",
//           volumes: [50, 100],
//           prices: [61900, 97900],
//           tags: ["우디", "중성적", "성숙한", "비누향", "오피스"],
//           content: "네롤리와 샌달우드가 조화로운 고급 우디 퍼퓸.",
//           detailContent: "깔끔한 네롤리 향이 시작을 알리고, 이어지는 우디 노트가 깊은 인상을 남깁니다. 깔끔하고 세련된 분위기를 완성합니다.",
//         },
//       },
//       {
//         _id: await nextSeq("product"),
//         seller_id: 1,
//         price: 32000,
//         show: true,
//         active: true,
//         name: "블랑쉬 플로르 퍼퓸",
//         quantity: 150,
//         buyQuantity: 88,
//         mainImages: [
//           {
//             path: `files/${clientId}/perfume7.webp`,
//             name: "perfume7.webp",
//             originalname: "블랑쉬플로르.webp",
//           },
//         ],
//         createdAt: getTime(-41, -60 * 60 * 2),
//         updatedAt: getTime(-40, -60 * 15),
//         extra: {
//           mainAccord: "floral",
//           brand: "랑방",
//           brandInitialKR: "ㄹ",
//           volumes: [30, 50, 90],
//           prices: [46900, 72900, 92900],
//           tags: ["플로럴", "여성스러움", "비누향", "봄", "샤워코롱"],
//           content: "깨끗한 꽃 향이 피부에 스며드는 듯한 부드러운 퍼퓸.",
//           detailContent: "은은한 백합과 자스민이 조화롭게 어우러지며 깔끔한 느낌을 줍니다. 하루 종일 기분 좋게 지속되는 향입니다.",
//         },
//       },
//       {
//         _id: await nextSeq("product"),
//         seller_id: 1,
//         price: 32000,
//         show: true,
//         active: true,
//         name: "코튼 머스크 퍼퓸",
//         quantity: 150,
//         buyQuantity: 66,
//         mainImages: [
//           {
//             path: `files/${clientId}/perfume8.webp`,
//             name: "perfume8.webp",
//             originalname: "코튼머스크.webp",
//           },
//         ],
//         createdAt: getTime(-41, -60 * 60 * 2),
//         updatedAt: getTime(-40, -60 * 15),
//         extra: {
//           mainAccord: "musk",
//           brand: "이솝",
//           brandInitialKR: "ㅇ",
//           volumes: [50, 100],
//           prices: [54900, 87900],
//           tags: ["머스크", "솜향", "살냄새", "데일리", "샤워코롱"],
//           content: "마치 방금 샤워한 듯한 깨끗한 무드를 주는 머스크 퍼퓸.",
//           detailContent: "섬유유연제처럼 부드럽고 포근한 머스크 향이 매력적입니다. 누구나 부담 없이 사용 가능한 데일리 향수입니다.",
//         },
//       },
//       {
//         _id: await nextSeq("product"),
//         seller_id: 1,
//         price: 32000,
//         show: true,
//         active: true,
//         name: "바닐라 슈가 퍼퓸",
//         quantity: 150,
//         buyQuantity: 74,
//         mainImages: [
//           {
//             path: `files/${clientId}/perfume9.webp`,
//             name: "perfume9.webp",
//             originalname: "바닐라슈가.webp",
//           },
//         ],
//         createdAt: getTime(-41, -60 * 60 * 2),
//         updatedAt: getTime(-40, -60 * 15),
//         extra: {
//           mainAccord: "sweet",
//           brand: "겐조",
//           brandInitialKR: "ㄱ",
//           volumes: [30, 70, 100],
//           prices: [49900, 78900, 95900],
//           tags: ["달콤함", "바닐라", "부드러움", "겨울", "따뜻함"],
//           content: "달콤한 바닐라와 슈가 노트가 감각을 자극하는 겨울 퍼퓸.",
//           detailContent: "스윗한 바닐라와 설탕 향이 어우러져 따뜻한 분위기를 자아냅니다. 추운 계절에 어울리는 포근한 향기입니다.",
//         },
//       },
//       {
//         _id: await nextSeq("product"),
//         seller_id: 1,
//         price: 32000,
//         show: true,
//         active: true,
//         name: "레몬 민트 퍼퓸",
//         quantity: 150,
//         buyQuantity: 91,
//         mainImages: [
//           {
//             path: `files/${clientId}/perfume10.webp`,
//             name: "perfume10.webp",
//             originalname: "레몬민트.webp",
//           },
//         ],
//         createdAt: getTime(-41, -60 * 60 * 2),
//         updatedAt: getTime(-40, -60 * 15),
//         extra: {
//           mainAccord: "citrus",
//           brand: "프레쉬",
//           brandInitialKR: "ㅍ",
//           volumes: [50, 100],
//           prices: [45900, 82900],
//           tags: ["시트러스", "상큼함", "민트", "여름", "샤워코롱"],
//           content: "상큼한 레몬과 시원한 민트가 만나 청량감을 선사하는 퍼퓸.",
//           detailContent: "산뜻한 레몬 향과 민트의 쿨링감이 만나 무더운 날씨에도 상쾌함을 유지해주는 여름 필수 향수입니다.",
//         },
//       },
//       {
//         _id: await nextSeq("product"),
//         seller_id: 1,
//         price: 32000,
//         show: true,
//         active: true,
//         name: "시더레인 퍼퓸",
//         quantity: 150,
//         buyQuantity: 52,
//         mainImages: [
//           {
//             path: `files/${clientId}/perfume11.webp`,
//             name: "perfume11.webp",
//             originalname: "시더레인.webp",
//           },
//         ],
//         createdAt: getTime(-41, -60 * 60 * 2),
//         updatedAt: getTime(-40, -60 * 15),
//         extra: {
//           mainAccord: "woody",
//           brand: "산타마리아노벨라",
//           brandInitialKR: "ㅅ",
//           volumes: [50, 100],
//           prices: [58900, 96900],
//           tags: ["우디", "비오는날", "나무향", "감성", "중성적"],
//           content: "촉촉한 나무향이 잔잔히 스며드는 우디 퍼퓸.",
//           detailContent: "시더우드와 머스크가 조화를 이루며 마치 숲 속을 걷는 듯한 차분함을 선사합니다. 비 오는 날, 감성적인 분위기와 잘 어울립니다.",
//         },
//       },
//       {
//         _id: await nextSeq("product"),
//         seller_id: 1,
//         price: 32000,
//         show: true,
//         active: true,
//         name: "피오니 블러쉬 퍼퓸",
//         quantity: 150,
//         buyQuantity: 76,
//         mainImages: [
//           {
//             path: `files/${clientId}/perfume12.webp`,
//             name: "perfume12.webp",
//             originalname: "피오니블러쉬.webp",
//           },
//         ],
//         createdAt: getTime(-41, -60 * 60 * 2),
//         updatedAt: getTime(-40, -60 * 15),
//         extra: {
//           mainAccord: "floral",
//           brand: "조말론",
//           brandInitialKR: "ㅈ",
//           volumes: [30, 50, 100],
//           prices: [49900, 76900, 93900],
//           tags: ["플로럴", "부드러움", "사랑스러움", "샤워코롱", "여성스러움"],
//           content: "부드럽고 사랑스러운 작약 향이 포근한 인상을 주는 퍼퓸.",
//           detailContent: "피오니의 은은한 플로럴 노트와 깨끗한 베이스가 조화를 이루며, 가볍고 우아한 향기를 완성합니다.",
//         },
//       },
//       {
//         _id: await nextSeq("product"),
//         seller_id: 1,
//         price: 32000,
//         show: true,
//         active: true,
//         name: "스킨 머스크 퍼퓸",
//         quantity: 150,
//         buyQuantity: 68,
//         mainImages: [
//           {
//             path: `files/${clientId}/perfume13.webp`,
//             name: "perfume13.webp",
//             originalname: "스킨머스크.webp",
//           },
//         ],
//         createdAt: getTime(-41, -60 * 60 * 2),
//         updatedAt: getTime(-40, -60 * 15),
//         extra: {
//           mainAccord: "musk",
//           brand: "더바디샵",
//           brandInitialKR: "ㄷ",
//           volumes: [50, 100],
//           prices: [41900, 74900],
//           tags: ["머스크", "살냄새", "자연스러움", "무향같은향", "데일리"],
//           content: "은은한 머스크 향이 피부에 스며들 듯 자연스러운 퍼퓸.",
//           detailContent: "가볍고 부드러운 머스크 노트로, 마치 본연의 체취처럼 자연스럽게 어우러집니다. 데일리용으로 적합합니다.",
//         },
//       },
//       {
//         _id: await nextSeq("product"),
//         seller_id: 1,
//         price: 32000,
//         show: true,
//         active: true,
//         name: "허니 플럼 퍼퓸",
//         quantity: 150,
//         buyQuantity: 84,
//         mainImages: [
//           {
//             path: `files/${clientId}/perfume14.webp`,
//             name: "perfume14.webp",
//             originalname: "허니플럼.webp",
//           },
//         ],
//         createdAt: getTime(-41, -60 * 60 * 2),
//         updatedAt: getTime(-40, -60 * 15),
//         extra: {
//           mainAccord: "sweet",
//           brand: "딥디크",
//           brandInitialKR: "ㄷ",
//           volumes: [30, 70, 100],
//           prices: [53900, 78900, 98900],
//           tags: ["달콤함", "꿀향", "플럼", "포근함", "샤워코롱"],
//           content: "달콤한 꿀과 자두 향이 풍성하게 퍼지는 스위트 퍼퓸.",
//           detailContent: "따뜻한 허니 노트와 과일 향이 어우러져 부드럽고 포근한 향기를 만들어냅니다. 기분전환용으로도 탁월합니다.",
//         },
//       },
//       {
//         _id: await nextSeq("product"),
//         seller_id: 1,
//         price: 32000,
//         show: true,
//         active: true,
//         name: "자몽티 퍼퓸",
//         quantity: 150,
//         buyQuantity: 93,
//         mainImages: [
//           {
//             path: `files/${clientId}/perfume15.webp`,
//             name: "perfume15.webp",
//             originalname: "자몽티.webp",
//           },
//         ],
//         createdAt: getTime(-41, -60 * 60 * 2),
//         updatedAt: getTime(-40, -60 * 15),
//         extra: {
//           mainAccord: "citrus",
//           brand: "불가리",
//           brandInitialKR: "ㅂ",
//           volumes: [50, 90],
//           prices: [55900, 88900],
//           tags: ["시트러스", "자몽", "티향", "상큼함", "여름"],
//           content: "자몽의 상큼함과 티의 부드러움이 조화를 이루는 시트러스 퍼퓸.",
//           detailContent: "산뜻한 자몽 향으로 시작해 은은한 티 베이스가 마무리되는 구조. 깔끔하면서도 여운이 오래가는 향기입니다.",
//         },
//       },
//       [
//         {
//           _id: await nextSeq("product"),
//           seller_id: 1,
//           price: 32000,
//           show: true,
//           active: true,
//           name: "블랙 우드 퍼퓸",
//           quantity: 150,
//           buyQuantity: 72,
//           mainImages: [
//             {
//               path: `files/${clientId}/perfume16.webp`,
//               name: "perfume16.webp",
//               originalname: "블랙우드.webp",
//             },
//           ],
//           createdAt: getTime(-41, -60 * 60 * 2),
//           updatedAt: getTime(-40, -60 * 15),
//           extra: {
//             mainAccord: "woody",
//             brand: "딥디크",
//             brandInitialKR: "ㄷ",
//             volumes: [50, 100],
//             prices: [59900, 94900],
//             tags: ["우디", "짙은향", "중후함", "남성적", "겨울"],
//             content: "짙은 나무 향과 스파이시함이 어우러진 고급스러운 퍼퓸.",
//             detailContent: "샌달우드와 베티버가 주를 이루며, 깊이감 있는 중후한 무드를 전달합니다. 추운 날씨와 잘 어울리는 향기입니다.",
//           },
//         },
//         {
//           _id: await nextSeq("product"),
//           seller_id: 1,
//           price: 32000,
//           show: true,
//           active: true,
//           name: "로즈 페탈 퍼퓸",
//           quantity: 150,
//           buyQuantity: 64,
//           mainImages: [
//             {
//               path: `files/${clientId}/perfume17.webp`,
//               name: "perfume17.webp",
//               originalname: "로즈페탈.webp",
//             },
//           ],
//           createdAt: getTime(-41, -60 * 60 * 2),
//           updatedAt: getTime(-40, -60 * 15),
//           extra: {
//             mainAccord: "floral",
//             brand: "조말론",
//             brandInitialKR: "ㅈ",
//             volumes: [30, 50, 100],
//             prices: [50900, 77900, 95900],
//             tags: ["플로럴", "장미", "부드러움", "로맨틱", "여성스러움"],
//             content: "장미 꽃잎을 그대로 담아낸 듯한 순수한 플로럴 퍼퓸.",
//             detailContent: "로즈 오일의 깊은 향과 은은한 비누향이 어우러져 우아하고 로맨틱한 분위기를 연출합니다.",
//           },
//         },
//         {
//           _id: await nextSeq("product"),
//           seller_id: 1,
//           price: 32000,
//           show: true,
//           active: true,
//           name: "화이트 머스크 샤워코롱",
//           quantity: 150,
//           buyQuantity: 87,
//           mainImages: [
//             {
//               path: `files/${clientId}/perfume18.webp`,
//               name: "perfume18.webp",
//               originalname: "화이트머스크.webp",
//             },
//           ],
//           createdAt: getTime(-41, -60 * 60 * 2),
//           updatedAt: getTime(-40, -60 * 15),
//           extra: {
//             mainAccord: "musk",
//             brand: "더바디샵",
//             brandInitialKR: "ㄷ",
//             volumes: [50, 100],
//             prices: [44900, 79900],
//             tags: ["머스크", "샤워코롱", "깨끗함", "가벼움", "중성적"],
//             content: "샤워 직후의 깨끗한 느낌을 담은 머스크 기반의 코롱.",
//             detailContent: "비누 향을 닮은 가벼운 머스크가 은은하게 퍼지며, 일상에서 부담 없이 사용할 수 있는 데일리 향입니다.",
//           },
//         },
//         {
//           _id: await nextSeq("product"),
//           seller_id: 1,
//           price: 32000,
//           show: true,
//           active: true,
//           name: "카라멜 블룸 퍼퓸",
//           quantity: 150,
//           buyQuantity: 91,
//           mainImages: [
//             {
//               path: `files/${clientId}/perfume19.webp`,
//               name: "perfume19.webp",
//               originalname: "카라멜블룸.webp",
//             },
//           ],
//           createdAt: getTime(-41, -60 * 60 * 2),
//           updatedAt: getTime(-40, -60 * 15),
//           extra: {
//             mainAccord: "sweet",
//             brand: "산타마리아노벨라",
//             brandInitialKR: "ㅅ",
//             volumes: [50, 80, 100],
//             prices: [57900, 82900, 99900],
//             tags: ["달콤함", "카라멜", "따뜻함", "포근함", "겨울"],
//             content: "달콤한 카라멜과 따뜻한 향신료가 어우러지는 스위트 퍼퓸.",
//             detailContent: "처음엔 부드러운 설탕 향이, 이어서 따뜻한 바닐라와 향신료가 감싸 안는 듯한 포근한 향입니다.",
//           },
//         },
//         {
//           _id: await nextSeq("product"),
//           seller_id: 1,
//           price: 32000,
//           show: true,
//           active: true,
//           name: "자몽버스트 퍼퓸",
//           quantity: 150,
//           buyQuantity: 75,
//           mainImages: [
//             {
//               path: `files/${clientId}/perfume20.webp`,
//               name: "perfume20.webp",
//               originalname: "자몽버스트.webp",
//             },
//           ],
//           createdAt: getTime(-41, -60 * 60 * 2),
//           updatedAt: getTime(-40, -60 * 15),
//           extra: {
//             mainAccord: "citrus",
//             brand: "불가리",
//             brandInitialKR: "ㅂ",
//             volumes: [50, 100],
//             prices: [52900, 86900],
//             tags: ["시트러스", "자몽", "상큼함", "프레시", "샤워코롱"],
//             content: "자몽 특유의 상큼함이 폭발하는 시트러스 계열 퍼퓸.",
//             detailContent: "상쾌한 자몽 노트가 첫 느낌을 잡아주고, 뒤이어 맑은 그린과 플로럴 노트가 부드럽게 이어집니다.",
//           },
//         },
//         {
//           _id: await nextSeq("product"),
//           seller_id: 1,
//           price: 32000,
//           show: true,
//           active: true,
//           name: "플로럴 그린 퍼퓸",
//           quantity: 150,
//           buyQuantity: 88,
//           mainImages: [
//             {
//               path: `files/${clientId}/perfume21.webp`,
//               name: "perfume21.webp",
//               originalname: "플로럴그린.webp",
//             },
//           ],
//           createdAt: getTime(-41, -60 * 60 * 2),
//           updatedAt: getTime(-40, -60 * 15),
//           extra: {
//             mainAccord: "floral",
//             brand: "조말론",
//             brandInitialKR: "ㅈ",
//             volumes: [30, 50, 100],
//             prices: [49900, 76900, 93900],
//             tags: ["플로럴", "그린노트", "자연", "청량함", "봄"],
//             content: "초록 잎사귀와 꽃의 조화를 담은 싱그러운 퍼퓸.",
//             detailContent: "풀잎이 스치는 듯한 그린노트와 신선한 플로럴이 어우러져 생기 넘치는 향을 선사합니다.",
//           },
//         },
//       ],
//     ],

//     // 주문
//     order: [
//       {
//         _id: await nextSeq("order"),
//         user_id: 1,
//         products: [
//           {
//             _id: 2,
//             name: "헬로카봇 스톰다이버",
//             image: {
//               path: `files/${clientId}/sample-diver.jpg`,
//               name: "sample-diver.jpg",
//               originalname: "헬로카봇.jpg",
//             },
//             quantity: 2,
//             price: 34520,
//             // review_id: 3, 리뷰 작성한 구매내역이면 리뷰아이디를 patch해야함
//           },
//         ],
//         cost: {
//           total: 34520,
//         },
//         createdAt: getTime(-6, -60 * 60 * 3),
//         updatedAt: getTime(-6, -60 * 60 * 3),
//       },
//     ],

//     // 후기
//     review: [
//       {
//         _id: await nextSeq("review"),
//         user: {
//           _id: 3,
//         },
//         order_id: 1,
//         product_id: 2,
//         rating: 5,
//         content: "아이가 좋아해요.",
//         createdAt: getTime(-4, -60 * 60 * 12),
//         extra: { images: [`files/${clientId}/perfume1.webp`, `files/${clientId}/perfume2.webp`, `files/${clientId}/perfume3.webp`, `files/${clientId}/perfume4.webp`] },
//       },
//     ],

//     // 장바구니
//     cart: [],

//     // 즐겨찾기/북마크
//     bookmark: [
//       {
//         _id: await nextSeq("bookmark"),
//         user_id: 1,
//         user: {
//           _id: 1,
//           name: "제이지",
//           image: `files/${clientId}/user-jayg.webp`,
//         },
//         type: "product",
//         target_id: 4,
//         createdAt: getTime(-3, -60 * 60 * 2),
//       },
//     ],

//     // QnA, 공지사항 등의 게시판
//     post: [
//       {
//         _id: await nextSeq("post"),
//         type: "post",
//         user: {
//           _id: 2,
//           name: "네오",
//           image: `files/${clientId}/user-neo.png`,
//         },
//         extra: {
//           answers: [1, 2, 3, 4, 4],
//           products: [4, 5, 1],
//         },
//         createdAt: getTime(-1, -60 * 60 * 14),
//         updatedAt: getTime(-1, -60 * 60 * 2),
//       },
//     ],

//     // 코드
//     code: [],

//     // 설정
//     config: [],
//   };
// };
